### ISSUE TITLE
Possible to not pass message_if_xl?

### ISSUE THREAD

**Issue by mamo-muj** [CodelyTV/pr-size-labeler#55]
Asking this because I basically want the PR size label on my PRs but what I don't want is to see the message as the team knows there's gonna be big PRs every now and then.

Not sure if returning an empty string would just not display it but would love to know a workaround for this 🙏

**Comment by Borda** [comment]
I second this; it would be great if setting an empty message would not comment at all...
For the context, the messages are are still cumulating as brought in #19

**Comment by elijaholmos** [comment]
Yeah, I can confirm that in both `v1.8.1` and the current version of main (d269449310fe33526c56b2dfe6244e3a9f489b15), passing an empty string into `message_if_xl` will not issue a comment on the PR.

In v1.8.1, it fails due to a GitHub API validation error. For details, view https://github.com/elijaholmos/ci-cd-playground/actions/runs/5720924462/job/15501687058?pr=78
